cources/urls.py
from django.urls import path
from .views import hompage,cources,authentication,cource_checkout


urlpatterns = [
    path('',hompage.index,name='index'),
    path('cource/<str:slug>',cources.courcesPage,name='courcepage'),
    path('signup/',authentication.signup,name='signup'), 
    path('login/',authentication.signin,name='login'), 
    path('logout/',authentication.signout,name='logout'), 
    path('checkout/<str:slug>',cource_checkout.checkout,name='checkout'), 
    path('verify_payment',cource_checkout.verifyPayment,name='verify_payment'), 
] 

gdemy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from .import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cources.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cources/models.py
from django.db import models

# Create your models here.

cources/models/cource.py
from django.db import models

class Cource(models.Model):
    name = models.CharField(max_length = 50, null = False)
    slug = models.CharField(max_length = 50, null = False, unique = True)
    desc = models.TextField(max_length=500, null=True)
    prince = models.IntegerField(null=False)
    discount = models.IntegerField(null=False, default=0)
    active = models.BooleanField(default = False)
    thumbnail = models.ImageField(upload_to='files/thumbnail')
    date = models.DateTimeField(auto_now_add = True)
    resource = models.FileField(upload_to='files/resources')
    length = models.IntegerField(null=False)

    def __str__(self):
        return self.name

class Hashtag(models.Model):
    tag = models.CharField(max_length=20, null =False)
    cource = models.ForeignKey(Cource, null=False, on_delete = models.CASCADE)


class Prerequisite(models.Model):
    required = models.CharField(max_length=20, null =False)
    cource = models.ForeignKey(Cource, null=False, on_delete = models.CASCADE)

class Learning(models.Model):
    tech_learn = models.CharField(max_length=20, null =False)
    cource = models.ForeignKey(Cource, null=False, on_delete = models.CASCADE)

cources/models/payment.py
from django.db import models
from .cource import Cource
from .user_cource import UserCource 
from django.contrib.auth.models import User

class Payment(models.Model):
    order_id = models.CharField(max_length = 50, null = False)
    payment_id = models.CharField(max_length = 50)
    user_cource = models.ForeignKey(UserCource, null=True, on_delete = models.CASCADE)
    cource = models.ForeignKey(Cource, null=False, on_delete = models.CASCADE)
    user = models.ForeignKey(User, null=False, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

cources/models/user_cource.py
from django.db import models
from .cource import Cource
from django.contrib.auth.models import User

class UserCource(models.Model):
    user = models.ForeignKey(User, null=False, on_delete=models.CASCADE)
    cource = models.ForeignKey(Cource, null=False, on_delete = models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username} - {self.cource.name}'

cources/models/videos.py
from unittest.util import _MAX_LENGTH
from django.db import models
from .cource import Cource

class Videos(models.Model):
    title = models.CharField(max_length = 50, null = False)
    cource = models.ForeignKey(Cource, null=False, on_delete = models.CASCADE)
    length = models.IntegerField(null=False)
    video_id = models.CharField(max_length = 20, null = False) 
    is_preview = models.BooleanField(default = False)

    def __str__(self):
        return self.title

cources/forms/login_form.py
from django.contrib.auth.forms import AuthenticationForm
from django import forms

class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=50, required=True, widget=forms.TextInput(attrs={'autofocus':True, 'class':'form-control'}))
    password = forms.CharField(label=('Password'), strip=False, widget=forms.PasswordInput(attrs={'autocomplete':'current-password', 'class':'form-control'}))
   
 

cources/forms/registration_forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.forms import ValidationError

class RegistrationForm(UserCreationForm):
    first_name = forms.CharField(max_length=50, required=True, widget=forms.TextInput(attrs={'autofocus':True, 'class':'form-control '}))
    last_name = forms.CharField(max_length=50, required=True, widget=forms.TextInput(attrs={'autofocus':True, 'class':'form-control'}))
    username = forms.CharField(max_length=50, required=True, widget=forms.TextInput(attrs={'autofocus':True, 'class':'form-control'}))
    email = forms.EmailField(max_length=50, required=True, widget=forms.TextInput(attrs={'autofocus':True, 'class':'form-control'}))
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password2 = forms.CharField(label='Confirm Password (again)', widget=forms.PasswordInput(attrs={'class':'form-control'}))
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']

    def clean_email(self):
        email =  self.cleaned_data['email']
        user = None
        try:
            user = User.objects.get(email = email)
        except:
            return email
        
        if user is not None:
            return ValidationError('User alreqady Exists ..!!')

cources/views/authentication.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from cources.models.cource import *
from cources.forms.registration_forms import RegistrationForm
from cources.forms.login_form import LoginForm
from django.contrib.auth import authenticate, login, logout

def signup(request):
    if request.method == 'GET':
        form = RegistrationForm()
        context = {
            'form':form
        }
        return render(request, 'cources/signup.html', context)
    form = RegistrationForm(request.POST)
    if form.is_valid():
        user = form.save()
        if user:
            return redirect('login')
    return render(request, 'cources/signup.html',  context = {'form':form} )
    # elif request.method == 'POST':
    #     return HttpResponse('posrt')
        

def signin(request):
    if request.method == 'GET':
        login_form = LoginForm()
        login_context = {
            'login_form': login_form
        }
        return render(request, 'cources/login.html', login_context)
    else:
        login_form = LoginForm(request=request,data=request.POST)
        login_context = {
                'login_form': login_form
            }
        if login_form.is_valid():
            print('///////////////')
            username = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']
            print('username is ....',username)
            print('password is ....',password)
            user = authenticate(username = username, password = password)
            if user is not None:
                login(request, user) 
                return redirect('index')
        print('not done')
        return render(request, 'cources/login.html', login_context)

        
def signout(request):
    logout(request)
    return redirect('index')

cources/views/cource_checkout.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from cources.models.cource import *
from cources.models.videos import Videos
from cources.models.payment import Payment
from cources.models.user_cource import UserCource
import razorpay
from django.views.decorators.csrf import csrf_exempt 
from gdemy.settings import KEY_SECRET, KEY_ID
client = razorpay.Client(auth=(KEY_ID, KEY_SECRET))
from time import time

def checkout(request, slug):
    # print(request.user)
    cource = Cource.objects.get(slug=slug)
    user = None
    if not request.user.is_authenticated:
        return redirect('login')
    user = request.user
    action = request.GET.get('action')
    order = None
    error_msg = None
    if action == 'create_payment':
        try:
            user_cource = UserCource.objects.get(user=user,cource=cource)
            error_msg = "You are Already Enrolled in this Course" 
        except:
            pass
        if error_msg is None:
            data = {
            'amount' : (cource.prince)*100,
            'currency' : 'INR',
            # 'reciept' : f'gdemy-{int(time())}',
            'notes' : {
                'email': user.email,
                'name': f'{user.first_name} {user.last_name}',
            },
            }
            order = client.order.create(data=data)
            payment = Payment()
            payment.user = user
            payment.cource = cource
            payment.order_id = order.get('id')
            payment.save()

        print('creating order object')
    data = {'cources':cource,
            'order':order,
            'error_msg': error_msg
            }
    return render(request, 'cources/checkout.html', data)


@csrf_exempt    
def verifyPayment(request):
    if request.method == 'POST':
        data = request.POST
        print('this is dataaa//.,..')
        print(data)
        razor_id = data.get('razorpay_order_id')
        razor_payment_id = data.get('razorpay_payment_id')
        razor_signature = data.get('razorpay_signature')
        params_dict = {
            'razorpay_order_id': razor_id,
            'razorpay_payment_id': razor_payment_id,
            'razorpay_signature': razor_signature
        }


# updating the payment model with payment.id and status 
        payment = Payment.objects.get(order_id=razor_id)
        payment.payment_id = razor_payment_id
        payment.status = True
        payment.save()


#  creating usercource in model 
        user_cource = UserCource()
        user_cource.user = payment.user
        user_cource.cource = payment.cource
        user_cource.save() 

# updating the payment model with payment.id and status 
        payment.user_cource = user_cource
        payment.save()




        context = {
            'data': params_dict
        }
        print('this is dict...',params_dict)
        try:
            return render(request, 'cources/my_cources.html', context)
            # client.utility.verify_payment_signature(params_dict)
        except:
            return HttpResponse('invalid payment')

cources/views/hompage.py
from django.http import HttpResponse
from django.shortcuts import render
from cources.models.cource import *

def index(request):
    cources = Cource.objects.all()
    data = {'cources':cources}
    return render(request, 'cources/index.html', data)

cources/templates/cources/checkout.html
{% extends './base.html' %}

{% block content %}



<div class="container">

    <h2 class="text-center">Checkout Page</h2> 
</div>
<div class="row">
    <div class="col mr-auto">

        <div class="float-right">
            <div class="card" style="width: 18rem;">

                <img src="{{cources.thumbnail.url}}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{cources.name}}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">Rs. {{cources.prince}}</h6>
                </div>
            </div>

        </div>

    </div>
    <div class="col p-3">
        <h3>{{cources.name}}</h3>
        <p>Total Payable Amount: Rs.{{cources.prince}}</p>
        <a href="?action=create_payment" class="btn btn-primary">Continue To Payment</a>



    </div>
</div>
<div>
    <h4 class="ml-3 mt-3">Description</h4>
    <p class="card-text ml-3 ">{{cources.desc}}</p>
</div>


{% if order is not None %}
<!-- <h1>Order popup {{order}}</h1> -->
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>
    var options = {
        "key": "rzp_test_L0QhXaFIY9o25u", // Enter the Key ID generated from the Dashboard
        // "amount": "50000", // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise
        // "currency": "INR",
        "name": "Acme Corp",
        "description": "Test Transaction",
        "image": "https://example.com/your_logo",
        "order_id": "{{order.id}}", //This is a sample Order ID. Pass the `id` obtained in the response of Step 2
        // "handler": function (response) {
        //     alert(response.razorpay_payment_id);
        //     alert(response.razorpay_order_id);
        //     alert(response.razorpay_signature)
        // },
        "callback_url": "http://127.0.0.1:8000/verify_payment",
        "prefill": {
            "name": "Gaurav Kumar",
            "email": "gaurav.kumar@example.com",
            "contact": "9999999999"
        },
        "theme": {
            "color": "#3399cc"
        }
    };
    var rzp1 = new Razorpay(options);
    // rzp1.on('payment.failed', function (response) {
    //     alert(response.error.code);
    //     alert(response.error.description);
    //     alert(response.error.source);
    //     alert(response.error.step);
    //     alert(response.error.reason);
    //     alert(response.error.metadata.order_id);
    //     alert(response.error.metadata.payment_id);
    // });

    // document.getElementById('rzp-button1').onclick = function (e) {
    //     rzp1.open();
    //     e.preventDefault();
    // }
    rzp1.open();
</script>
{% endif %}
{% if error_msg is not None %}
<script>
    window.onload = ()=>{
        alert("{{error_msg}}")
    }
</script>
{% endif %}
{% endblock %}

cources/templates/cources/cource_page.html
{% extends './base.html' %}

{% block content %}
<style>
    #outerrow{
        overflow-y: scroll;
        height: 485px !important;

    }
    .active-video{
        background-color: rgb(0 0 0 / 23%);
    }
</style>
{{video_id}}
<div class="container-fluid">
    <!-- <div hidden>
        <h1>{{cources}}</h1>
        <h1>{{cources.name}}</h1>
        <p>{{cources.desc}}</p>

        <p>{{cources.videos_set.all}}</p>
        tags ...........
        <p>{{cources.hashtag_set.all}}</p>
        requisits ...........
        <p>{{cources.prerequisite_set.all}}</p>
        learning ..............
        <p>{{cources.learning_set.all}}</p>
    </div> -->
    {{video.video_id}}
    <div>
        <div class="row">
            <div class="col">
                <div>
                    <iframe id="player" height="315" width="100%" src="https://www.youtube.com/embed/{{video.video_id}}"
                        title="YouTube video player" frameborder="0"
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                        allowfullscreen></iframe>
                </div>
            </div>
            <div class="col-4" id="outerrow" >
                <ul class="list-group">
                    {% for v in cources.videos_set.all %}
                    <li class="list-group-item {% if v == video %} active-video {% endif %}"><a href="?video={{v.id}}">{{v}}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="mt-3">
            <h3>{{cources.name}}</h3>
            {{cources.desc}}
        </div>
        <div class="mt-3">
            <a href="/checkout/{{cources.slug}}" class="btn btn-primary mr-2 justify-content-center d-flex align-items-center"><i class="fas fa-link"></i> Enrol l Now</a>
            <h4>Things You'll Learn</h4>
            {% for learn in cources.learning_set.all %}
            <div class="d-inline p-2 bg-primary text-white mr-2">
                {{learn.tech_learn}}
            </div>
            {% endfor %}
        </div>
        <div class="mt-3">
            <h4>Tags</h4>
            {% for tag in cources.hashtag_set.all %}
            <div class="d-inline p-2 bg-primary text-white mr-2">
                {{tag.tag}}
            </div>
            {% endfor %}
        </div>
        <div class="mt-3">
            <h4>Prerequisits</h4>
            {% for pre in cources.prerequisite_set.all %}
            <div class="d-inline p-2 bg-primary text-white mr-2">
                {{pre.required}}
            </div>
            {% endfor %}
        </div>
    </div>
</div>


<script>
    var player;
    var video_list
    window.onload = ()=>{
        player = document.getElementById('player')
        video_list = document.getElementById('video_list')
        maintainratio()
    }
    function maintainratio(){
        var w = player.clientWidth
        var h = (w*9)/16
        player.height = h
    }
    video_list.style.maxHeight = 4 + 'px'
    window.onresize = maintainratio()
</script>


{% endblock %}

cources/templates/cources/index.html
{% extends './base.html' %}

{% block content %}
<style>
    :root {
        --gradient: linear-gradient(to left top, #0e8ce4 10%, #5f91a9 90%) !important;
    }

    body {
        background: rgb(215, 215, 215) !important;
    }

    .card {
        background: #222;
        border: 1px solid #dd2476;
        color: rgba(250, 250, 250, 0.8);
        margin-bottom: 2rem;
    }

    .btn {
        border: 5px solid;
        border-image-slice: 1;
        background: var(--gradient) !important;
        -webkit-background-clip: text !important;
        -webkit-text-fill-color: transparent !important;
        border-image-source: var(--gradient) !important;
        text-decoration: none;
        transition: all .4s ease;
    }

    .btn:hover,
    .btn:focus {
        background: var(--gradient) !important;
        -webkit-background-clip: none !important;
        -webkit-text-fill-color: #fff !important;
        border: 5px solid #fff !important;
        box-shadow: #222 1px 0 10px;
        text-decoration: underline;
    }
</style>

<div class="container">
    {{request.user}}
    <div class="row ">
        {%  for cource in cources %}
            
            <div class="col-sm-3">
                <div class="card" style="width: 18rem;">
                    
                <img src="{{cource.thumbnail.url}}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{cource.name}}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">Rs. {{cource.prince}}</h6>
                    <!-- <p class="card-text">{{cource.desc}}</p> -->
                    <a href="checkout/{{cource.slug}}" class="btn btn-primary mr-2"><i class="fas fa-link"></i> Enrool Now</a>
                    <a href="/cource/{{cource.slug}}" class="btn btn-primary"><i class="fab fa-github"></i> Show More</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

cources/templates/cources/login.html
{% extends './base.html' %}

{% block content %}

<h1>login</h1>

<form action="" method="POST" novalidate class="shadow p-5">
    {% csrf_token %}
    {{login_form}}
    <br>
    <input type="submit" value="Submit" class="btn btn-primary">
</form>
{% endblock %}

cources/templates/cources/my_cources.html
{% extends './base.html' %}

{% block content %}
<h1>done</h1>

{% endblock %}

cources/templates/cources/signup.html
{% extends './base.html' %}

{% block content %}

<h1>signup</h1>

<form action="" method="POST" novalidate class="shadow p-5">
    {% csrf_token %}
    {{form}}
    <br>
    <input type="submit" value="Submit" class="btn btn-primary">
</form>
{% endblock %}